# Generated by Django 2.2.7 on 2019-11-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pensum',
            options={'verbose_name': 'Pensum', 'verbose_name_plural': 'Pensums'},
        ),
        migrations.RemoveField(
            model_name='curso',
            name='seccion',
        ),
    ]
